# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170805_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choicetext',
            new_name='choice_text',
        ),
    ]
