# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170807_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choicetext',
        ),
    ]
